CC=g++
LD=g++

CCFLAGS=-O2 -I. 
LDFLAGS=-O2 

TARGETS=ballwalk ballwalk_adaptive hitandrun gaussian gaussian_adaptive
SHARED_OBJECTS=shared.o main.o
BALLWALK_OBJECTS=ballwalk.o
BALLWALK_ADAPTIVE_OBJECTS=ballwalk_adaptive.o
GAUSSIAN_OBJECTS=gaussian.o
GAUSSIAN_ADAPTIVE_OBJECTS=gaussian_adaptive.o
HITANDRUN_OBJECTS=hitandrun.o

all: $(TARGETS)

ballwalk: $(SHARED_OBJECTS) $(BALLWALK_OBJECTS)
	$(LD) -o ballwalk $(LDFLAGS) $(SHARED_OBJECTS) $(BALLWALK_OBJECTS)

ballwalk_adaptive: $(SHARED_OBJECTS) $(BALLWALK_ADAPTIVE_OBJECTS)
	$(LD) -o ballwalk_adaptive $(LDFLAGS) $(SHARED_OBJECTS) $(BALLWALK_ADAPTIVE_OBJECTS)

hitandrun: $(SHARED_OBJECTS) $(HITANDRUN_OBJECTS)
	$(LD) -o hitandrun $(LDFLAGS) $(SHARED_OBJECTS) $(HITANDRUN_OBJECTS)

gaussian: $(SHARED_OBJECTS) $(GAUSSIAN_OBJECTS)
	$(LD) -o gaussian $(LDFLAGS) $(SHARED_OBJECTS) $(GAUSSIAN_OBJECTS)

gaussian_adaptive: $(SHARED_OBJECTS) $(GAUSSIAN_ADAPTIVE_OBJECTS)
	$(LD) -o gaussian_adaptive $(LDFLAGS) $(SHARED_OBJECTS) $(GAUSSIAN_ADAPTIVE_OBJECTS)

clean:
	rm -f $(TARGETS) $(SHARED_OBJECTS) $(BALLWALK_OBJECTS) $(HITANDRUN_OBJECTS) $(BALLWALK_ADAPTIVE_OBJECTS) $(GAUSSIAN_OBJECTS) $(GAUSSIAN_ADAPTIVE_OBJECTS)

%.o: %.cpp
	$(CC) -c $(CCFLAGS) $<
